import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Movie from '../models/Movie.js';

dotenv.config();

// TMDB image base URL - w500 size posters
const IMG = 'https://image.tmdb.org/t/p/w500';

const sampleMovies = [
  {
    movieId: 1,
    title: "The Shawshank Redemption",
    genres: ["Drama", "Crime"],
    year: 1994,
    director: "Frank Darabont",
    actors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    plot: "Two imprisoned men bond over years, finding redemption through acts of common decency.",
    poster: `${IMG}/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg`,
    averageRating: 4.8,
    totalRatings: 250,
    popularity: 950,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 2,
    title: "The Dark Knight",
    genres: ["Action", "Crime", "Drama"],
    year: 2008,
    director: "Christopher Nolan",
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    plot: "Batman faces his greatest challenge yet as the Joker wreaks havoc on Gotham City.",
    poster: `${IMG}/qJ2tW6WMUDux911kpUpRVQalRMK.jpg`,
    averageRating: 4.7,
    totalRatings: 320,
    popularity: 1200,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 3,
    title: "Inception",
    genres: ["Action", "Sci-Fi", "Thriller"],
    year: 2010,
    director: "Christopher Nolan",
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    plot: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a C.E.O.",
    poster: `${IMG}/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg`,
    averageRating: 4.6,
    totalRatings: 280,
    popularity: 1100,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 4,
    title: "Pulp Fiction",
    genres: ["Crime", "Drama"],
    year: 1994,
    director: "Quentin Tarantino",
    actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    plot: "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster: `${IMG}/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg`,
    averageRating: 4.5,
    totalRatings: 210,
    popularity: 850,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 5,
    title: "Forrest Gump",
    genres: ["Drama", "Romance"],
    year: 1994,
    director: "Robert Zemeckis",
    actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    plot: "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with a low IQ.",
    poster: `${IMG}/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg`,
    averageRating: 4.7,
    totalRatings: 300,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 6,
    title: "The Matrix",
    genres: ["Action", "Sci-Fi"],
    year: 1999,
    director: "Lana Wachowski",
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    plot: "A hacker discovers that reality as he knows it is a simulated reality created by machines, and joins a rebellion to free humanity.",
    poster: `${IMG}/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg`,
    averageRating: 4.6,
    totalRatings: 290,
    popularity: 1050,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 7,
    title: "Interstellar",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    year: 2014,
    director: "Christopher Nolan",
    actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: `${IMG}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg`,
    averageRating: 4.5,
    totalRatings: 270,
    popularity: 920,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 8,
    title: "The Lion King",
    genres: ["Animation", "Adventure", "Drama"],
    year: 1994,
    director: "Roger Allers",
    actors: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
    plot: "A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    poster: `${IMG}/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg`,
    averageRating: 4.4,
    totalRatings: 240,
    popularity: 890,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 9,
    title: "The Avengers",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2012,
    director: "Joss Whedon",
    actors: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    plot: "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
    poster: `${IMG}/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg`,
    averageRating: 4.3,
    totalRatings: 350,
    popularity: 1300,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 10,
    title: "Parasite",
    genres: ["Comedy", "Drama", "Thriller"],
    year: 2019,
    director: "Bong Joon-ho",
    actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    poster: `${IMG}/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg`,
    averageRating: 4.6,
    totalRatings: 220,
    popularity: 780,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 11,
    title: "The Godfather",
    genres: ["Crime", "Drama"],
    year: 1972,
    director: "Francis Ford Coppola",
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
    poster: `${IMG}/3bhkrj58Vtu7enYsRolD1fZdja1.jpg`,
    averageRating: 4.9,
    totalRatings: 310,
    popularity: 1150,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 12,
    title: "Titanic",
    genres: ["Drama", "Romance"],
    year: 1997,
    director: "James Cameron",
    actors: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
    plot: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
    poster: `${IMG}/9xjZS2rlVxm8SFx8kFB3985I7Bi.jpg`,
    averageRating: 4.4,
    totalRatings: 380,
    popularity: 1400,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 13,
    title: "The Silence of the Lambs",
    genres: ["Crime", "Drama", "Thriller"],
    year: 1991,
    director: "Jonathan Demme",
    actors: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn"],
    plot: "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    poster: `${IMG}/uS9m8OBk1RVfUPbA04xMDX084kE.jpg`,
    averageRating: 4.5,
    totalRatings: 200,
    popularity: 720,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 14,
    title: "Spirited Away",
    genres: ["Animation", "Adventure", "Fantasy"],
    year: 2001,
    director: "Hayao Miyazaki",
    actors: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    plot: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    poster: `${IMG}/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg`,
    averageRating: 4.7,
    totalRatings: 260,
    popularity: 870,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 15,
    title: "Gladiator",
    genres: ["Action", "Adventure", "Drama"],
    year: 2000,
    director: "Ridley Scott",
    actors: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    plot: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    poster: `${IMG}/ty8TGRuvJLPUmAR1H1nRIsgCLin.jpg`,
    averageRating: 4.5,
    totalRatings: 290,
    popularity: 950,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 16,
    title: "Joker",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2019,
    director: "Todd Phillips",
    actors: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    plot: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral.",
    poster: `${IMG}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg`,
    averageRating: 4.4,
    totalRatings: 300,
    popularity: 1020,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 17,
    title: "The Prestige",
    genres: ["Drama", "Mystery", "Thriller"],
    year: 2006,
    director: "Christopher Nolan",
    actors: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"],
    plot: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.",
    poster: `${IMG}/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg`,
    averageRating: 4.5,
    totalRatings: 230,
    popularity: 810,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 18,
    title: "Avatar",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 2009,
    director: "James Cameron",
    actors: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    plot: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following orders and protecting an alien civilization.",
    poster: `${IMG}/kyeqWdyUXW608qlYkRqosgbbJyK.jpg`,
    averageRating: 4.3,
    totalRatings: 420,
    popularity: 1500,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 19,
    title: "The Green Mile",
    genres: ["Crime", "Drama", "Fantasy"],
    year: 1999,
    director: "Frank Darabont",
    actors: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
    plot: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    poster: `${IMG}/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg`,
    averageRating: 4.6,
    totalRatings: 250,
    popularity: 880,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 20,
    title: "Whiplash",
    genres: ["Drama", "Music"],
    year: 2014,
    director: "Damien Chazelle",
    actors: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    plot: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
    poster: `${IMG}/7fn624j5lj3xTme2SgiLCeuedmO.jpg`,
    averageRating: 4.5,
    totalRatings: 210,
    popularity: 740,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  // ===== NEW MOVIES ADDED BELOW =====
  {
    movieId: 21,
    title: "Fight Club",
    genres: ["Drama", "Thriller"],
    year: 1999,
    director: "David Fincher",
    actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    poster: `${IMG}/pB8BM7pdSp6B6Ih7QI4DrQ3PmJK.jpg`,
    averageRating: 4.7,
    totalRatings: 340,
    popularity: 1100,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 22,
    title: "Goodfellas",
    genres: ["Crime", "Drama"],
    year: 1990,
    director: "Martin Scorsese",
    actors: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    plot: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    poster: `${IMG}/aKuFiU82s5ISJDx4hDNx8kHAUmE.jpg`,
    averageRating: 4.6,
    totalRatings: 280,
    popularity: 920,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 23,
    title: "Se7en",
    genres: ["Crime", "Drama", "Mystery"],
    year: 1995,
    director: "David Fincher",
    actors: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"],
    plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    poster: `${IMG}/6yoghtyTpznpBik8UrBEyOGMOR7.jpg`,
    averageRating: 4.6,
    totalRatings: 260,
    popularity: 880,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 24,
    title: "The Departed",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2006,
    director: "Martin Scorsese",
    actors: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
    plot: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    poster: `${IMG}/nT97ifVT2J1yMQmeq20Dqv60Su.jpg`,
    averageRating: 4.5,
    totalRatings: 300,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 25,
    title: "Django Unchained",
    genres: ["Drama", "Western"],
    year: 2012,
    director: "Quentin Tarantino",
    actors: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
    plot: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
    poster: `${IMG}/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg`,
    averageRating: 4.5,
    totalRatings: 310,
    popularity: 1050,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 26,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genres: ["Adventure", "Drama", "Fantasy"],
    year: 2001,
    director: "Peter Jackson",
    actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.",
    poster: `${IMG}/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg`,
    averageRating: 4.8,
    totalRatings: 350,
    popularity: 1200,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 27,
    title: "The Lord of the Rings: The Return of the King",
    genres: ["Adventure", "Drama", "Fantasy"],
    year: 2003,
    director: "Peter Jackson",
    actors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    poster: `${IMG}/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg`,
    averageRating: 4.9,
    totalRatings: 340,
    popularity: 1180,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 28,
    title: "Spider-Man: Into the Spider-Verse",
    genres: ["Animation", "Action", "Adventure"],
    year: 2018,
    director: "Bob Persichetti",
    actors: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    plot: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions.",
    poster: `${IMG}/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg`,
    averageRating: 4.7,
    totalRatings: 290,
    popularity: 1020,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 29,
    title: "The Social Network",
    genres: ["Biography", "Drama"],
    year: 2010,
    director: "David Fincher",
    actors: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake"],
    plot: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.",
    poster: `${IMG}/n0ybibhJtQ5icDqTp8eRhcXz1la.jpg`,
    averageRating: 4.4,
    totalRatings: 250,
    popularity: 830,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 30,
    title: "Schindler's List",
    genres: ["Biography", "Drama", "History"],
    year: 1993,
    director: "Steven Spielberg",
    actors: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"],
    plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
    poster: `${IMG}/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg`,
    averageRating: 4.9,
    totalRatings: 310,
    popularity: 1050,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 31,
    title: "Saving Private Ryan",
    genres: ["Drama", "War"],
    year: 1998,
    director: "Steven Spielberg",
    actors: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
    plot: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    poster: `${IMG}/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg`,
    averageRating: 4.6,
    totalRatings: 290,
    popularity: 960,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 32,
    title: "The Wolf of Wall Street",
    genres: ["Biography", "Comedy", "Crime"],
    year: 2013,
    director: "Martin Scorsese",
    actors: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"],
    plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime and corruption.",
    poster: `${IMG}/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg`,
    averageRating: 4.4,
    totalRatings: 330,
    popularity: 1100,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 33,
    title: "Mad Max: Fury Road",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2015,
    director: "George Miller",
    actors: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    plot: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners and a drifter.",
    poster: `${IMG}/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg`,
    averageRating: 4.5,
    totalRatings: 310,
    popularity: 1060,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 34,
    title: "Jurassic Park",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 1993,
    director: "Steven Spielberg",
    actors: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
    plot: "A pragmatic paleontologist touring an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
    poster: `${IMG}/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg`,
    averageRating: 4.4,
    totalRatings: 350,
    popularity: 1200,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 35,
    title: "Back to the Future",
    genres: ["Adventure", "Comedy", "Sci-Fi"],
    year: 1985,
    director: "Robert Zemeckis",
    actors: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
    plot: "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend Dr. Emmett Brown.",
    poster: `${IMG}/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg`,
    averageRating: 4.6,
    totalRatings: 330,
    popularity: 1100,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 36,
    title: "The Truman Show",
    genres: ["Comedy", "Drama"],
    year: 1998,
    director: "Peter Weir",
    actors: ["Jim Carrey", "Ed Harris", "Laura Linney"],
    plot: "An insurance salesman discovers his whole life is actually a reality TV show.",
    poster: `${IMG}/vuza0WqY239yBXOadKlGwJsZJFE.jpg`,
    averageRating: 4.5,
    totalRatings: 270,
    popularity: 890,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 37,
    title: "Toy Story",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 1995,
    director: "John Lasseter",
    actors: ["Tom Hanks", "Tim Allen", "Don Rickles"],
    plot: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
    poster: `${IMG}/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg`,
    averageRating: 4.4,
    totalRatings: 300,
    popularity: 960,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 38,
    title: "WALL-E",
    genres: ["Animation", "Adventure", "Family"],
    year: 2008,
    director: "Andrew Stanton",
    actors: ["Ben Burtt", "Elissa Knight", "Jeff Garlin"],
    plot: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    poster: `${IMG}/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg`,
    averageRating: 4.5,
    totalRatings: 280,
    popularity: 920,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 39,
    title: "Coco",
    genres: ["Animation", "Adventure", "Family"],
    year: 2017,
    director: "Lee Unkrich",
    actors: ["Anthony Gonzalez", "Gael Garcia Bernal", "Benjamin Bratt"],
    plot: "Aspiring musician Miguel, confronted with his family's ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    poster: `${IMG}/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg`,
    averageRating: 4.6,
    totalRatings: 290,
    popularity: 970,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 40,
    title: "Get Out",
    genres: ["Horror", "Mystery", "Thriller"],
    year: 2017,
    director: "Jordan Peele",
    actors: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford"],
    plot: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    poster: `${IMG}/qbaIViTEeEDIBlGMaFaKGMSJbLb.jpg`,
    averageRating: 4.4,
    totalRatings: 270,
    popularity: 880,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 41,
    title: "La La Land",
    genres: ["Comedy", "Drama", "Music"],
    year: 2016,
    director: "Damien Chazelle",
    actors: ["Ryan Gosling", "Emma Stone", "Rosemarie DeWitt"],
    plot: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    poster: `${IMG}/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg`,
    averageRating: 4.4,
    totalRatings: 310,
    popularity: 1030,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 42,
    title: "The Grand Budapest Hotel",
    genres: ["Adventure", "Comedy", "Crime"],
    year: 2014,
    director: "Wes Anderson",
    actors: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric"],
    plot: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glory years.",
    poster: `${IMG}/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg`,
    averageRating: 4.4,
    totalRatings: 260,
    popularity: 850,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 43,
    title: "Black Panther",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2018,
    director: "Ryan Coogler",
    actors: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    plot: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and confront a challenger from his country's past.",
    poster: `${IMG}/uxzzxijgPIY7slzFvMotPv8wjKA.jpg`,
    averageRating: 4.3,
    totalRatings: 340,
    popularity: 1150,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 44,
    title: "Avengers: Endgame",
    genres: ["Action", "Adventure", "Drama"],
    year: 2019,
    director: "Anthony Russo",
    actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    plot: "After the devastating events of Infinity War, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    poster: `${IMG}/or06FN3Dka5tukK1e9sl16pB3iy.jpg`,
    averageRating: 4.5,
    totalRatings: 400,
    popularity: 1500,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 45,
    title: "Guardians of the Galaxy",
    genres: ["Action", "Adventure", "Comedy"],
    year: 2014,
    director: "James Gunn",
    actors: ["Chris Pratt", "Vin Diesel", "Bradley Cooper"],
    plot: "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    poster: `${IMG}/r7vmZjiyZw9rpJMQJdLpkprMKPH.jpg`,
    averageRating: 4.4,
    totalRatings: 320,
    popularity: 1080,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 46,
    title: "Everything Everywhere All at Once",
    genres: ["Action", "Adventure", "Comedy"],
    year: 2022,
    director: "Daniel Kwan",
    actors: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan"],
    plot: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    poster: `${IMG}/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg`,
    averageRating: 4.6,
    totalRatings: 290,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 47,
    title: "Dune",
    genres: ["Action", "Adventure", "Drama"],
    year: 2021,
    director: "Denis Villeneuve",
    actors: ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya"],
    plot: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    poster: `${IMG}/d5NXSklXo0qyIYkgV94XAgMIckC.jpg`,
    averageRating: 4.4,
    totalRatings: 310,
    popularity: 1050,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 48,
    title: "Oppenheimer",
    genres: ["Biography", "Drama", "History"],
    year: 2023,
    director: "Christopher Nolan",
    actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    plot: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    poster: `${IMG}/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg`,
    averageRating: 4.5,
    totalRatings: 330,
    popularity: 1120,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 49,
    title: "John Wick",
    genres: ["Action", "Crime", "Thriller"],
    year: 2014,
    director: "Chad Stahelski",
    actors: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen"],
    plot: "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
    poster: `${IMG}/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg`,
    averageRating: 4.3,
    totalRatings: 310,
    popularity: 1030,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 50,
    title: "The Batman",
    genres: ["Action", "Crime", "Drama"],
    year: 2022,
    director: "Matt Reeves",
    actors: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright"],
    plot: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    poster: `${IMG}/74xTEgt7R36Fpooo50r9T25onhq.jpg`,
    averageRating: 4.3,
    totalRatings: 300,
    popularity: 1000,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 51,
    title: "Eternal Sunshine of the Spotless Mind",
    genres: ["Drama", "Romance", "Sci-Fi"],
    year: 2004,
    director: "Michel Gondry",
    actors: ["Jim Carrey", "Kate Winslet", "Tom Wilkinson"],
    plot: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.",
    poster: `${IMG}/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg`,
    averageRating: 4.5,
    totalRatings: 260,
    popularity: 840,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 52,
    title: "No Country for Old Men",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2007,
    director: "Joel Coen",
    actors: ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin"],
    plot: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
    poster: `${IMG}/bj1v6YKF8yHqA489GFfAWcKINvK.jpg`,
    averageRating: 4.5,
    totalRatings: 270,
    popularity: 870,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 53,
    title: "The Incredibles",
    genres: ["Animation", "Action", "Adventure"],
    year: 2004,
    director: "Brad Bird",
    actors: ["Craig T. Nelson", "Holly Hunter", "Samuel L. Jackson"],
    plot: "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
    poster: `${IMG}/2LqaLgk1653EMKyNtLUqbkPjg07.jpg`,
    averageRating: 4.4,
    totalRatings: 310,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 54,
    title: "Up",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2009,
    director: "Pete Docter",
    actors: ["Edward Asner", "Jordan Nagai", "John Ratzenberger"],
    plot: "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
    poster: `${IMG}/vpbaStTMt8qqXaEgnOR2EE4DNsE.jpg`,
    averageRating: 4.5,
    totalRatings: 290,
    popularity: 940,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 55,
    title: "Blade Runner 2049",
    genres: ["Action", "Drama", "Sci-Fi"],
    year: 2017,
    director: "Denis Villeneuve",
    actors: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    poster: `${IMG}/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg`,
    averageRating: 4.4,
    totalRatings: 260,
    popularity: 850,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 56,
    title: "Arrival",
    genres: ["Drama", "Mystery", "Sci-Fi"],
    year: 2016,
    director: "Denis Villeneuve",
    actors: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
    plot: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    poster: `${IMG}/x2FJsf1ElAgr63Y3LNxZq57Brmu.jpg`,
    averageRating: 4.4,
    totalRatings: 270,
    popularity: 860,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 57,
    title: "The Revenant",
    genres: ["Action", "Adventure", "Drama"],
    year: 2015,
    director: "Alejandro G. Iñárritu",
    actors: ["Leonardo DiCaprio", "Tom Hardy", "Domhnall Gleeson"],
    plot: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
    poster: `${IMG}/ji3ecJphATlVgWNY0B4RKm5JTQ3.jpg`,
    averageRating: 4.3,
    totalRatings: 310,
    popularity: 1020,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 58,
    title: "Bohemian Rhapsody",
    genres: ["Biography", "Drama", "Music"],
    year: 2018,
    director: "Bryan Singer",
    actors: ["Rami Malek", "Lucy Boynton", "Gwilym Lee"],
    plot: "The story of the legendary British rock band Queen and lead singer Freddie Mercury, leading up to their famous performance at Live Aid.",
    poster: `${IMG}/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg`,
    averageRating: 4.3,
    totalRatings: 330,
    popularity: 1080,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 59,
    title: "Knives Out",
    genres: ["Comedy", "Crime", "Drama"],
    year: 2019,
    director: "Rian Johnson",
    actors: ["Daniel Craig", "Chris Evans", "Ana de Armas"],
    plot: "A detective investigates the death of the patriarch of an eccentric, combative family.",
    poster: `${IMG}/pThyQovXQrw2m0s9x82twj48Jq4.jpg`,
    averageRating: 4.4,
    totalRatings: 280,
    popularity: 920,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 60,
    title: "1917",
    genres: ["Drama", "War"],
    year: 2019,
    director: "Sam Mendes",
    actors: ["Dean-Charles Chapman", "George MacKay", "Daniel Mays"],
    plot: "Two young British soldiers during WWI are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men from walking into a deadly trap.",
    poster: `${IMG}/iZf0KyrE25z1sage4SYFDuEQFBJ.jpg`,
    averageRating: 4.4,
    totalRatings: 290,
    popularity: 930,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 61,
    title: "Iron Man",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2008,
    director: "Jon Favreau",
    actors: ["Robert Downey Jr.", "Gwyneth Paltrow", "Terrence Howard"],
    plot: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    poster: `${IMG}/78lPtwv72eTNqFW9COBYI0dWDJa.jpg`,
    averageRating: 4.3,
    totalRatings: 340,
    popularity: 1120,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 62,
    title: "Star Wars: A New Hope",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 1977,
    director: "George Lucas",
    actors: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    plot: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station.",
    poster: `${IMG}/6FfCtHuRtzLmano8MiaqA8V5lmQ.jpg`,
    averageRating: 4.7,
    totalRatings: 370,
    popularity: 1300,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 63,
    title: "Star Wars: The Empire Strikes Back",
    genres: ["Action", "Adventure", "Fantasy"],
    year: 1980,
    director: "Irvin Kershner",
    actors: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    plot: "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda while his friends are pursued across the galaxy by Darth Vader.",
    poster: `${IMG}/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg`,
    averageRating: 4.8,
    totalRatings: 360,
    popularity: 1250,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 64,
    title: "Shutter Island",
    genres: ["Mystery", "Thriller"],
    year: 2010,
    director: "Martin Scorsese",
    actors: ["Leonardo DiCaprio", "Emily Mortimer", "Mark Ruffalo"],
    plot: "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
    poster: `${IMG}/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg`,
    averageRating: 4.4,
    totalRatings: 300,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 65,
    title: "Memento",
    genres: ["Mystery", "Thriller"],
    year: 2000,
    director: "Christopher Nolan",
    actors: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"],
    plot: "A man with short-term memory loss attempts to track down his wife's murderer.",
    poster: `${IMG}/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg`,
    averageRating: 4.5,
    totalRatings: 240,
    popularity: 800,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 66,
    title: "The Conjuring",
    genres: ["Horror", "Mystery", "Thriller"],
    year: 2013,
    director: "James Wan",
    actors: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor"],
    plot: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    poster: `${IMG}/wVYREutTvI2tmxr6ujrHT704wGF.jpg`,
    averageRating: 4.2,
    totalRatings: 310,
    popularity: 1020,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 67,
    title: "A Quiet Place",
    genres: ["Drama", "Horror", "Sci-Fi"],
    year: 2018,
    director: "John Krasinski",
    actors: ["Emily Blunt", "John Krasinski", "Millicent Simmonds"],
    plot: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
    poster: `${IMG}/nAU74GmpUk7t5iklEp3bufwDq4n.jpg`,
    averageRating: 4.3,
    totalRatings: 290,
    popularity: 950,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 68,
    title: "Inglourious Basterds",
    genres: ["Adventure", "Drama", "War"],
    year: 2009,
    director: "Quentin Tarantino",
    actors: ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent"],
    plot: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans.",
    poster: `${IMG}/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg`,
    averageRating: 4.5,
    totalRatings: 300,
    popularity: 970,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 69,
    title: "Inside Out",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2015,
    director: "Pete Docter",
    actors: ["Amy Poehler", "Bill Hader", "Lewis Black"],
    plot: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust, and Sadness - conflict on how best to navigate a new city.",
    poster: `${IMG}/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg`,
    averageRating: 4.5,
    totalRatings: 290,
    popularity: 950,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 70,
    title: "Finding Nemo",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2003,
    director: "Andrew Stanton",
    actors: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould"],
    plot: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.",
    poster: `${IMG}/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg`,
    averageRating: 4.4,
    totalRatings: 310,
    popularity: 980,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 71,
    title: "The Sixth Sense",
    genres: ["Drama", "Mystery", "Thriller"],
    year: 1999,
    director: "M. Night Shyamalan",
    actors: ["Bruce Willis", "Haley Joel Osment", "Toni Collette"],
    plot: "A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.",
    poster: `${IMG}/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg`,
    averageRating: 4.4,
    totalRatings: 270,
    popularity: 870,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 72,
    title: "Alien",
    genres: ["Horror", "Sci-Fi"],
    year: 1979,
    director: "Ridley Scott",
    actors: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
    plot: "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
    poster: `${IMG}/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg`,
    averageRating: 4.5,
    totalRatings: 280,
    popularity: 900,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 73,
    title: "Aliens",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 1986,
    director: "James Cameron",
    actors: ["Sigourney Weaver", "Michael Biehn", "Carrie Henn"],
    plot: "Decades after surviving the Nostromo incident, Ellen Ripley is sent back to the moon where her crew encountered the hostile Alien creatures.",
    poster: `${IMG}/r1x5JGpyqkM8YMJmWhND5MoEhQl.jpg`,
    averageRating: 4.5,
    totalRatings: 290,
    popularity: 920,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 74,
    title: "Ratatouille",
    genres: ["Animation", "Comedy", "Family"],
    year: 2007,
    director: "Brad Bird",
    actors: ["Patton Oswalt", "Ian Holm", "Lou Romano"],
    plot: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
    poster: `${IMG}/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg`,
    averageRating: 4.4,
    totalRatings: 300,
    popularity: 960,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 75,
    title: "The Terminator",
    genres: ["Action", "Sci-Fi"],
    year: 1984,
    director: "James Cameron",
    actors: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
    plot: "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine sent from the same year to kill a young woman.",
    poster: `${IMG}/qvktm0BHcnmDisA2cfrGYWq3Gm.jpg`,
    averageRating: 4.4,
    totalRatings: 280,
    popularity: 910,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 76,
    title: "Terminator 2: Judgment Day",
    genres: ["Action", "Sci-Fi"],
    year: 1991,
    director: "James Cameron",
    actors: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
    plot: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.",
    poster: `${IMG}/weVXMD5QBGeQil4HEATZqAkXf4F.jpg`,
    averageRating: 4.6,
    totalRatings: 310,
    popularity: 1010,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 77,
    title: "Gone Girl",
    genres: ["Drama", "Mystery", "Thriller"],
    year: 2014,
    director: "David Fincher",
    actors: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris"],
    plot: "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
    poster: `${IMG}/lv5xShBIDPe4O1gSEg5OQNQ3JM8.jpg`,
    averageRating: 4.4,
    totalRatings: 290,
    popularity: 940,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 78,
    title: "Moonlight",
    genres: ["Drama"],
    year: 2016,
    director: "Barry Jenkins",
    actors: ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes"],
    plot: "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.",
    poster: `${IMG}/4911T5FbJ9eD2Faz5Z8cT3SUhU3.jpg`,
    averageRating: 4.4,
    totalRatings: 240,
    popularity: 800,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 79,
    title: "The Hunger Games",
    genres: ["Action", "Adventure", "Sci-Fi"],
    year: 2012,
    director: "Gary Ross",
    actors: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
    plot: "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each district must fight to the death.",
    poster: `${IMG}/iWCVHFHELEbo7r5q2lT7OBEcJel.jpg`,
    averageRating: 4.2,
    totalRatings: 350,
    popularity: 1150,
    embedding: Array(64).fill(0).map(() => Math.random())
  },
  {
    movieId: 80,
    title: "Frozen",
    genres: ["Animation", "Adventure", "Comedy"],
    year: 2013,
    director: "Chris Buck",
    actors: ["Kristen Bell", "Idina Menzel", "Jonathan Groff"],
    plot: "When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man to change the weather condition.",
    poster: `${IMG}/kgwjIb2JDHRhNk13lmSNiQjgOkj.jpg`,
    averageRating: 4.2,
    totalRatings: 340,
    popularity: 1120,
    embedding: Array(64).fill(0).map(() => Math.random())
  }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/rl-recommendation');

    console.log('Connected to MongoDB');
    console.log('Clearing existing movies...');

    await Movie.deleteMany({});

    console.log('Inserting sample movies...');

    await Movie.insertMany(sampleMovies);

    console.log(`Successfully seeded ${sampleMovies.length} movies!`);
    console.log('Database seeding completed.');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
